name: Test

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  unit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['22', '24']
      fail-fast: false
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.version }}
          cache: npm
      - run: npm ci
      - run: npm test
